/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as LandlordIndexRouteImport } from './routes/landlord.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TenantReservationsRouteImport } from './routes/tenant.reservations'
import { Route as TenantPaymentsRouteImport } from './routes/tenant.payments'
import { Route as RoommateChatConversationIdRouteImport } from './routes/roommate-chat.$conversationId'
import { Route as LandlordReservationsRouteImport } from './routes/landlord.reservations'
import { Route as LandlordListingsRouteImport } from './routes/landlord.listings'
import { Route as DormsDormIdRouteImport } from './routes/dorms.$dormId'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const LandlordIndexRoute = LandlordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandlordRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantReservationsRoute = TenantReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPaymentsRoute = TenantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TenantRoute,
} as any)
const RoommateChatConversationIdRoute =
  RoommateChatConversationIdRouteImport.update({
    id: '/roommate-chat/$conversationId',
    path: '/roommate-chat/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandlordReservationsRoute = LandlordReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordListingsRoute = LandlordListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => LandlordRoute,
} as any)
const DormsDormIdRoute = DormsDormIdRouteImport.update({
  id: '/dorms/$dormId',
  path: '/dorms/$dormId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/landlord': typeof LandlordRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/dorms/$dormId': typeof DormsDormIdRoute
  '/landlord/listings': typeof LandlordListingsRoute
  '/landlord/reservations': typeof LandlordReservationsRoute
  '/roommate-chat/$conversationId': typeof RoommateChatConversationIdRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/reservations': typeof TenantReservationsRoute
  '/admin/': typeof AdminIndexRoute
  '/landlord/': typeof LandlordIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dorms/$dormId': typeof DormsDormIdRoute
  '/landlord/listings': typeof LandlordListingsRoute
  '/landlord/reservations': typeof LandlordReservationsRoute
  '/roommate-chat/$conversationId': typeof RoommateChatConversationIdRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/reservations': typeof TenantReservationsRoute
  '/admin': typeof AdminIndexRoute
  '/landlord': typeof LandlordIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/landlord': typeof LandlordRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/tenant': typeof TenantRouteWithChildren
  '/dorms/$dormId': typeof DormsDormIdRoute
  '/landlord/listings': typeof LandlordListingsRoute
  '/landlord/reservations': typeof LandlordReservationsRoute
  '/roommate-chat/$conversationId': typeof RoommateChatConversationIdRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/reservations': typeof TenantReservationsRoute
  '/admin/': typeof AdminIndexRoute
  '/landlord/': typeof LandlordIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/compare'
    | '/dashboard'
    | '/landlord'
    | '/login'
    | '/onboarding'
    | '/tenant'
    | '/dorms/$dormId'
    | '/landlord/listings'
    | '/landlord/reservations'
    | '/roommate-chat/$conversationId'
    | '/tenant/payments'
    | '/tenant/reservations'
    | '/admin/'
    | '/landlord/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/compare'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dorms/$dormId'
    | '/landlord/listings'
    | '/landlord/reservations'
    | '/roommate-chat/$conversationId'
    | '/tenant/payments'
    | '/tenant/reservations'
    | '/admin'
    | '/landlord'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/compare'
    | '/dashboard'
    | '/landlord'
    | '/login'
    | '/onboarding'
    | '/tenant'
    | '/dorms/$dormId'
    | '/landlord/listings'
    | '/landlord/reservations'
    | '/roommate-chat/$conversationId'
    | '/tenant/payments'
    | '/tenant/reservations'
    | '/admin/'
    | '/landlord/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  LandlordRoute: typeof LandlordRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  TenantRoute: typeof TenantRouteWithChildren
  DormsDormIdRoute: typeof DormsDormIdRoute
  RoommateChatConversationIdRoute: typeof RoommateChatConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/landlord/': {
      id: '/landlord/'
      path: '/'
      fullPath: '/landlord/'
      preLoaderRoute: typeof LandlordIndexRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/reservations': {
      id: '/tenant/reservations'
      path: '/reservations'
      fullPath: '/tenant/reservations'
      preLoaderRoute: typeof TenantReservationsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/roommate-chat/$conversationId': {
      id: '/roommate-chat/$conversationId'
      path: '/roommate-chat/$conversationId'
      fullPath: '/roommate-chat/$conversationId'
      preLoaderRoute: typeof RoommateChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/reservations': {
      id: '/landlord/reservations'
      path: '/reservations'
      fullPath: '/landlord/reservations'
      preLoaderRoute: typeof LandlordReservationsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/landlord/listings': {
      id: '/landlord/listings'
      path: '/listings'
      fullPath: '/landlord/listings'
      preLoaderRoute: typeof LandlordListingsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/dorms/$dormId': {
      id: '/dorms/$dormId'
      path: '/dorms/$dormId'
      fullPath: '/dorms/$dormId'
      preLoaderRoute: typeof DormsDormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LandlordRouteChildren {
  LandlordListingsRoute: typeof LandlordListingsRoute
  LandlordReservationsRoute: typeof LandlordReservationsRoute
  LandlordIndexRoute: typeof LandlordIndexRoute
}

const LandlordRouteChildren: LandlordRouteChildren = {
  LandlordListingsRoute: LandlordListingsRoute,
  LandlordReservationsRoute: LandlordReservationsRoute,
  LandlordIndexRoute: LandlordIndexRoute,
}

const LandlordRouteWithChildren = LandlordRoute._addFileChildren(
  LandlordRouteChildren,
)

interface TenantRouteChildren {
  TenantPaymentsRoute: typeof TenantPaymentsRoute
  TenantReservationsRoute: typeof TenantReservationsRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantPaymentsRoute: TenantPaymentsRoute,
  TenantReservationsRoute: TenantReservationsRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  LandlordRoute: LandlordRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  TenantRoute: TenantRouteWithChildren,
  DormsDormIdRoute: DormsDormIdRoute,
  RoommateChatConversationIdRoute: RoommateChatConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
